//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akhil.ProcessOrders.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAction
    {
        public int PaymentActionID { get; set; }
        public string PaymentActionCode { get; set; }
        public string PaymentActionCodeDescription { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<bool> CodeStatus { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
    }
}
